title: Clayton Jones # your name (or website title) here
logo: "/images/headshot.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 4+ years of experience turning data into actionable insights and solving real-world problems using statistical and analytical techniques.
  <br><br>
  Education:
  <br>
  Master of Science in Data Science – Northwestern University
  <br>
  Bachelor of Science in Industrial Engineering - Texas A&M University
  <br><br>
  <a href="https://www.linkedin.com/in/clayton-jones-8a989017a/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
